# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ol1662le-s/Program/stop_watch/stop_watch.cache/wt [current_project]
set_property parent.project_path C:/Users/ol1662le-s/Program/stop_watch/stop_watch.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/ol1662le-s/Program/stop_watch/stop_watch.srcs/sources_1/imports/vhdl/stop_watch_package.vhd
  C:/Users/ol1662le-s/Program/stop_watch/stop_watch.srcs/sources_1/imports/vhdl/edge_det.vhd
  C:/Users/ol1662le-s/Program/stop_watch/stop_watch.srcs/sources_1/imports/vhdl/seven_segment.vhd
  C:/Users/ol1662le-s/Program/stop_watch/stop_watch.srcs/sources_1/imports/vhdl/fsm.vhd
  C:/Users/ol1662le-s/Program/stop_watch/stop_watch.srcs/sources_1/imports/vhdl/nbcd.vhd
  C:/Users/ol1662le-s/Program/stop_watch/stop_watch.srcs/sources_1/imports/vhdl/counter.vhd
  C:/Users/ol1662le-s/Program/stop_watch/stop_watch.srcs/sources_1/imports/vhdl/stop_watch.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ol1662le-s/Program/stop_watch/stop_watch.srcs/constrs_1/imports/vhdl/top.xdc
set_property used_in_implementation false [get_files C:/Users/ol1662le-s/Program/stop_watch/stop_watch.srcs/constrs_1/imports/vhdl/top.xdc]


synth_design -top stop_watch -part xc7a100tcsg324-1


write_checkpoint -force -noxdef stop_watch.dcp

catch { report_utilization -file stop_watch_utilization_synth.rpt -pb stop_watch_utilization_synth.pb }
